---
- name: Install Frappe Bench on Ubuntu 24.04
  hosts: ubuntu
  become: true
  become_user: root
  pre_tasks:
    - name: Install required packages
      ansible.builtin.apt:
        name:
          - git
          - python-is-python3
          - python3-dev
          - python3-pip
          - redis-server
          - pkg-config
          - xvfb
          - libfontconfig
        state: present
        update_cache: true

    - name: Install wkhtmltopdf
      ansible.builtin.apt:
        deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb

  roles:
    - mariadb
    - node
    - bench
