---
- name: Playbook sheeeek
  hosts: ubuntu
  become: true
  become_user: root
  pre_tasks:
    - name: Include vars
      ansible.builtin.include_vars: vars.yml

    - name: Install required packages
      ansible.builtin.apt:
        name:
          - acl
          - git
          - python-is-python3
          - python3-dev
          - python3-pexpect
          - python3-pip
          - python3-venv
          - redis-server
          - pkg-config
          - xvfb
          - libfontconfig
        state: present
        update_cache: true

    - name: Install wkhtmltopdf
      ansible.builtin.apt:
        deb: https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/wkhtmltox_0.12.6.1-2.jammy_amd64.deb

    - name: Ensure sudo group does not ask for password
      ansible.builtin.lineinfile:
        path: /etc/sudoers
        regexp: ^%sudo
        line: '%sudo   ALL=(ALL:ALL) NOPASSWD: ALL'

  roles:
    - mariadb
    - node
    - bench
    - erpnext
