---
- name: Deploy ERPNext with Docker Compose
  hosts: all
  become: yes

  vars:
    target_dir: /opt/erpnext15
    source_config_dir: /etc/ansible/configs

  tasks:
    - name: Install required apt packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - software-properties-common
        state: present
        update_cache: yes

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name: docker-ce
        state: latest
        update_cache: yes

    - name: Install Docker Compose
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.24.6/docker-compose-linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'

    - name: Create target directory
      file:
        path: "{{ target_dir }}"
        state: directory
        mode: '0755'

    - name: Copy configuration files to target directory
      copy:
        src: "{{ item }}"
        dest: "{{ target_dir }}/"
      with_fileglob:
        - "{{ source_config_dir }}/*"

    - name: Start Docker Compose services
      command: docker-compose up -d
      args:
        chdir: "{{ target_dir }}"
      ignore_errors: yes    

